version: "3.8"
services:
  node:
    build:
      dockerfile: docker/node/Dockerfile
      context: .
    restart: unless-stopped
    environment:
      - FLAG=HZ{FAKE_FLAG}
    ports:
      - "0.0.0.0:1337:80"
