version: "3.8"
services:
  mathbot:
    build:
      context: ./tonogram
    environment:
      BOT_TOKEN_FILE: /run/secrets/mathbot_token
    secrets:
      - mathbot_token
secrets:
  mathbot_token:
    file: ./token.secret
