# syntax=docker/dockerfile:1
FROM golang:1.19 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY main.go .
COPY core ./core
RUN CGO_ENABLED=0 GOOS=linux go build -o /volga-vibes

FROM gcr.io/distroless/base-debian11

WORKDIR /app

COPY --from=builder /volga-vibes /app/volga-vibes
COPY certs ./certs

EXPOSE 3000

ENTRYPOINT ["/app/volga-vibes"]
