version: "3.8"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    environment:
      - FLAG=HZ{FAKE_FLAG}
    networks: [traefik]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.easier-hw.rule=Host(`easier-hw.challenge.haruulzangi.mn`)"
      - "traefik.http.routers.easier-hw.entrypoints=websecure"
      - "traefik.http.routers.easier-hw.tls.certresolver=myresolver"
