version: '3.8'
services:
  node:
    build:
      context: .
    restart: unless-stopped
    environment:
      - FLAG=HZ{FAKE_FLAG}
      - APP_SECRET=8tTXPilYZiI8lO2p1lUO3sWEGRJ9V9zLeA4Y3k3zP08
    volumes:
      - ./data:/usr/src/app/data
    networks: [traefik]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shopper.rule=Host(`shopper.challenge.haruulzangi.mn`)"
      - "traefik.http.routers.shopper.entrypoints=websecure"
      - "traefik.http.routers.shopper.tls.certresolver=myresolver"
networks:
  traefik:
    external: true
