version: "3.8"
services:
  shopper:
    build:
      context: ./shopper
    restart: unless-stopped
    environment:
      - FLAG=HZ{FAKE_FLAG}
      - APP_SECRET=8tTXPilYZiI8lO2p1lUO3sWEGRJ9V9zLeA4Y3k3zP08
    volumes:
      - shopper-db:/usr/src/app/data
    networks: [traefik]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shopper.rule=Host(`shopper.challenge.haruulzangi.mn`)"
      - "traefik.http.routers.shopper.entrypoints=websecure"
      - "traefik.http.routers.shopper.tls.certresolver=myresolver"
  easier-hw:
    build:
      context: ./easier-homework
    restart: unless-stopped
    environment:
      - FLAG=HZ{FAKE_FLAG}
    networks: [traefik]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.easier-hw.rule=Host(`easier-hw.challenge.haruulzangi.mn`)"
      - "traefik.http.routers.easier-hw.entrypoints=websecure"
      - "traefik.http.routers.easier-hw.tls.certresolver=myresolver"
networks:
  traefik:
    external: true
volumes:
  shopper-db: {}
